blog/urls.py
from django.urls import path
from . import views

urlpatterns = [ # IP주소/blog/
    path('',views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),     # post 관련 pk
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),              # comment 관련 pk
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),         # 괄호 안에 첫 번째가 url이고 두번째가 처리할 함수 호출 # IP주소/blog/category/slug
    path('tag/<str:slug>/', views.tag_page),     # IP주소/blog/tag/slug
    path('search/<str:q>/',views.PostSearch.as_view())


    #path('', views.index),  # IP주소/blog
    #path('<int:pk>/', views.single_post_page)
]

myDjangoPrj1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [     # IP 주소/
    path('admin/', admin.site.urls),    # IP 주소/admin
    path('blog/', include('blog.urls')),    # IP 주소/blog
    path('', include('single_pages.urls')),  # IP 주소/
    path('accounts/', include('allauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User  # 작성자 할 때 추가
import os

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):  # IP주소/blog/tag/slug
        return f'/blog/tag/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):                             # 카테고리부분
        return f'/blog/category/{self.slug}'

    class Meta:                                               # 카테고리부분
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)   # blank=True라고 하면 필수항목은 아니라는 뜻
    # %Y 2022, %y 22
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 추후 author 작성
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL) # null은 null이라는 값을 넣을수 있는것..  blank가 있어야 카테고리없는 거 허용
    tags = models.ManyToManyField(Tag, blank=True) # null = True 포함되어 있어서 적을 필요없음 on_delete도 마찬가지임.

    def __str__(self):
        return f'[{self.pk}]{self.title}:: {self.author} : {self.created_at}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):  # 템플릿에서 쓰는 이름과 반드시 같아야 한다.
        return self.get_file_name().split('.')[-1]  # 가장 마지막 배열의 원소. -1
        # a.txt  -> a txt
        # b.docx -> b docx
        # c.xlsx -> c xlsx
        # a.b.c.txt -> a b c txt

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)    # 왜 다대일 관계인지 다시 생각해보기.
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)  # 나머지는 다 자동으로 가져와 짐.

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag, Comment                             # 카테고리부분
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']  # , 'tags'
    # 템플릿 post_form

    template_name = 'blog/post_update_form.html' # 클래스에서도 직접적으로 템플릿을 부를 수 있다.

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)  # 태그 기존에 있는 거 가져오든지 아님 새로 만드는 행동함.
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)  # 슬러그까지 추가해서 저장.
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()                # string 배열들로 만들고 하나의 string으로 만듦.
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)      # 다 합쳐서 각각을 ;으로 구분하게 만듦.
        context['categories'] = Category.objects.all()                                   # 카테고리부분 사이드바 내용 위해 추가해줌.
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title','hook_text', 'content', 'head_image', 'file_upload','category'] # , 'tags' 태그 구분 딜리미터 , ; 만 씀.
    # 템플릿 post_form
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str') # POST 우리가 쓰고 있는 모델명이 아니라 사용자가 request할 떄 URL없이 비교적 긴 데이터 전달할 때 쓰는 전달 방식
            if tags_str :
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)       # 태그 기존에 있는 거 가져오든지 아님 새로 만드는 행동함.
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode = True)               # 슬러그까지 추가해서 저장.
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')

    # 템플릿 : 모델명_form.html
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostCreate, self).get_context_data()
        context['categories'] = Category.objects.all()                                   # 카테고리부분 사이드바 내용 위해 추가해줌.
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostList(ListView):
    model = Post
    ordering = '-pk' # 모델 이름만 설정하면 자동 호출 pk값이 작은 순서대로 보여달란 뜻임.
    paginate_by = 5 # 페이지네이션, 내용 나눠서 보여주는 것

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()                                   # 카테고리부분
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

    # 템플릿 모델명_list.html : post_list.html
    # 파라미터 모델명_list : post_list


class PostSearch(PostList): # ListView 상속, post_list, post_list.html
    paginate_by = None

    def get_queryset(self):                     # 영상 다시 보기
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q} ({self.get_queryset().count()})'
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):     # 카테고리부분
        context = super(PostDetail, self).get_context_data()    # 슈퍼 해당되는 내용 PostDetail임을 명심하자
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        return context

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)                     # 카테고리부분
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request, 'blog/post_list.html', {
        'category' : category,                                        # 템플릿이 사용하는 변수는 따옴표 안에 있음 :은 =과 같은 역할
        'post_list' : post_list,
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(request, 'blog/post_list.html', {
        'tag' : tag,
        'post_list': post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })

    # 템플릿 모델명_detail.html : post_detail.html
    # 파라미터 모델명 : post

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else: # GET
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    # CreateView, UpdateView, form을 사용하면
    # 템플릿 모델명_form : comment_form

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


# CBV방식에는 이게 필요함. 글 여러개 나타낼 때 필요 for문에서 post
#def index(request):
#    posts1 =Post.objects.all().order_by('-pk')    최신 포스트 부터 보여주기
#    return render(request, 'blog/index.html', {'posts': posts1})

#def single_post_page(request,pk):
#    post2 = Post.objects.get(pk=pk)
#    return render(request,'blog/single_post_page.html', {'post':post2})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
    <script src="https://kit.fontawesome.com/eca5e2617c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    {% include 'blog/navbar.html' %}

    <div class="container">
      <div class="row">
        <div class="col-md-8 col-lg-9" id="main-area">
          {% block main_area %}
          {% endblock %}
        </div>
        <div class="col-md-4 col-lg-3">
          {% include 'blog/sidebar.html' %}
        </div>

      </div>
    </div>
    {% include 'blog/footer.html' %} <!--copy&paste-->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
  <h1>Edit Comment</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/footer.html
      <!-- Footer-->
      <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; InternetProgramming 2022</p></div>
      </footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
  <h1>Blog</h1>

  {% for p in posts %}
  <h2> <a href="{{p.get_absolute_url}}"> {{p.title}} </a> </h2>
    <h3> {{p.created_at}} </h3>
    <p> {{p.content}} </p>
  {% endfor %}

</body>
</html>

blog/templates/blog/navbar.html
  {% load socialaccount %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">InternetProgramming</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/blog/">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about_me/">AboutMe</a>
            </li>

          </ul>
          <ul class="navbar-nav ml-auto">  <!-- ml-auto-->
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.socialaccount_set.all.0.get_avatar_url %}   <!--all.0 과 first는 같다.-->
                <img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" width="25px">
                {% else %}
                <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px">
                {% endif %}
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="#"  data-toggle="modal" data-target="#loginModal">LogIn</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> LogIn</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-6">
                <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                  href="{% provider_login_url 'google' %}">
                  <i class="fa-brands fa-google"></i> LogIn with Google
                </a>
                <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                  href="/accounts/login/">
                  <i class="fa-regular fa-envelope"></i> LogIn with Email
                </a>
              </div>
              <div class="col-6">
                <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                   href="/accounts/signup/">
                  <i class="fa-regular fa-envelope"></i> SignUp with Email
                </a>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{post.title}} - Blog
{% endblock %}

{% block main_area %}
                    <!-- Post content-->
                    <div id="post-area">
                        <!-- Post header 8개, 4개 해서 가로 12개로 나눌 수 있음. -->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title | lower}}</h1>   <!--소문자로 출력하기-->
                            {% if post.hook_text %}
                            <h5 class="text-muted">{{post.hook_text}}</h5>
                            {% endif %}
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">
                                Posted on {{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author | upper}}
                            </div>
                            <!-- Post categories-->
                            {% if post.category %}
                                <a class="badge bg-secondary text-decoration-none link-light"
                                   href="{{post.category.get_absolute_url}}">
                                    {{post.category}}
                                </a>
                            {% else %}
                                <a class="badge bg-secondary text-decoration-none link-light"
                                   href="/blog/category/no_category/">
                                    미분류
                                </a>
                            {% endif %}
                        </header>
                        <!-- 수정 페이지로 이동 -->
                        {% if user.is_authenticated and user == post.author %}
                             <a href="/blog/update_post/{{post.pk}}/" role="button"
                                class="btn btn-info btn-sm float-right">
                                <i class ="fas fa-pen"> Edit Post</i>
                             </a>
                        {% endif %}
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                            {% if post.head_image %}
                            <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{post.title}}의 head_image" />
                            {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image"/>
                            {% endif %}
                        </figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{post.content}}</p>
                            {% if post.tags.exists %}
                                <i class="fas fa-tag"></i>
                                {% for t in post.tags.iterator %}
                                    <span class="badge badge-pill badge-light">
                                        <a href="{{t.get_absolute_url}}">{{t}}</a>
                                    </span>
                                {% endfor %}
                                <br><br>
                            {% endif %}
                            {% if post.file_upload %}
                            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                                {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fa-regular fa-file-excel"></i>
                                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                                <i class="fa-regular fa-file-word"></i>
                                {% else %}
                                <i class="fa-regular fa-file"></i>
                                {% endif %}
                                Download {{post.get_file_name}} <!--함수이름임. model.py의. -->
                            </a>
                            {% endif %}
                        </section>
                    </div>
                    <!-- Comments section-->
                    <div id="comment-area" class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="post"
                                    action="{{post.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                                    data-toggle="modal" data-target="#loginModal">
                                    Log in and Leave a comment
                                </a>
                                {% endif %}
                                {% if post.comment_set.exists %}
                                {% for comment in post.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">
                                    <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px" />
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                            <a role="button" class="btn btn-sm btn-info float-right"
                                                href="/blog/update_comment/{{comment.pk}}/">
                                                Edit
                                            </a>
                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text-muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks }}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Create New Post</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str"
          class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Update Post</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}"
          class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/sidebar.html
<!--코드 일부가 들어 가는 것이기 때문에 html 형식 다 들고 오면 안 됨-->

          <!-- Search widget-->
          <div class="card mb-4">
              <div class="card-header"><i class="fa-solid fa-magnifying-glass"></i> Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
                    </div>
                </div>
          </div>
          <script>
              function searchPost(){
                searchValue = document.getElementById('search-input').value.trim();
                if( searchValue.length > 1 ){
                    // 검색 url view template
                    location.href = "/blog/search/"+ searchValue + "/";
                }
                else{
                    alert('검색어(' + searchValue + ')가 너무 짧아요.');
                }
              };

              document.getElementById('search-input').addEventListener(
                'keyup', function(event){
                    if(event.key === 'Enter'){  // 값과 타입 둘 다 비교해 줌. 안 됨 alert 창 추가해보기 껐다 다시 켜 보기 깃에 업로드 하기
                        searchPost();
                    }
                });
          </script>
          <!-- Categories widget-->
          <div class="card mb-4" id='category-card'>
              <div class="card-header">Categories</div>
              <div class="card-body">
                  <div class="row">
                          <ul class="list-unstyled mb-0">
                              {% for c in categories %}
                                <li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
                              {% endfor %}
                                <li><a href="/blog/category/no_category/">미분류 ({{no_category_post_count}})</a></li>
                          </ul>
                  </div>
              </div>
          </div>

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
  <h1>{{ post.title }}</h1>
  <h3>{{ post.created_at }}</h3>
  <p>{{ post.content }}</p>

    <hr />
    <h4>여기에 댓글을 넣으면 되겠죠?</h4>

</body>
</html>